version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: server run
          command: |
            cd server
            npm install
            npm start
      - run:
          name: client exec GET /
          command: |
            cd client
            ./get.sh
